# Generated by Django 4.1 on 2023-03-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_customer_customerorder_order_status_orderitem_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
